[package]
name = "benchmark-scratchpad"
version = "0.1.0"
edition = "2021"
rust-version = "1.58.0"
license = "MIT"

[dependencies]

[dev-dependencies]
criterion = "0.3.5"
benchmark_macro = { version = "0.1.0", path = "./crates/benchmark_macro" }

[[bench]]
name = "benchmark"
harness = false
